# Permanent Link Admin Commands
# Don't Remove Credit @CodeFlix_Bots, @rohit_1888

from pyrogram import Client, filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton
from bot import Bot
from config import PERMANENT_LINKS, BLOGSPOT_URL, BLOGSPOT_PARAM
from helper_func import admin

@Bot.on_message(filters.private & admin & filters.command('permanent_info'))
async def permanent_info(client: Client, message: Message):
    """Show permanent link system information"""
    
    if PERMANENT_LINKS and BLOGSPOT_URL:
        status = f"""
✅ **PERMANENT LINK SYSTEM ACTIVE**

**Configuration:**
• Blogspot URL: `{BLOGSPOT_URL}`
• URL Parameter: `{BLOGSPOT_PARAM}`
• Current Bot: @{client.username}

**How it works:**
1. When you use `/batch` or `/genlink` commands
2. Bot generates permanent links using Blogspot
3. Users click Blogspot link → Redirects to current bot
4. If bot gets banned → Create new bot → Update Blogspot HTML → All links continue working!

**Links generated by:**
• `/batch` - Batch file links ✓
• `/genlink` - Single file links ✓
• `/custom_batch` - Custom batch links ✓
• Channel forward - Direct links (not permanent)

**To update after bot ban:**
1. Edit Blogspot HTML file
2. Change: `const CURRENT_BOT_USERNAME = "new_bot_username";`
3. Save and publish
4. Done! All existing links will work
        """
    else:
        status = f"""
❌ **DIRECT LINK SYSTEM ACTIVE**

**Current Links:**
• `/batch` - Direct Telegram links
• `/genlink` - Direct Telegram links
• Format: `https://t.me/{client.username}?start=encoded_string`

⚠️ **Warning:** All links will stop working if bot gets banned!

**Enable Permanent Links:**
Add to config.py or environment:
